[package]
name = "os_base"
version = "0.1.0"
authors = ["Daniele <lupo.develop@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.6.4"
volatile = "0.2.6"


[profile.dev]
panic = "abort"

[profile.relase]
panic = "abort"